name: the_alphermix
description: "Ignite your imagination with The Alphermix, the elegant mobile app where two ideas beautifully collide to spark genuinely novel business concepts, brought to life through a delightful, animation-rich interface."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  http: ^1.0.0
  shared_preferences: ^2.0.0
  lottie: ^3.0.0
  rive: 0.14.0-dev.13
  flutter_animate: ^4.0.0
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
